require('drakúnom.telescope')
require('drakúnom.lightline')
require('drakúnom.gitsigns')
require('drakúnom.lsp-zero')
--require('drakúnom.bufferline')
require('drakúnom.nvim-tree')
require('drakúnom.scope')
